### ISSUE TITLE
Lesson 3 - Markdown

### ISSUE THREAD

**Issue by smileycreations15** [smileycreations88/lesson-1#5]
This lesson will be about markdown.
Emojis(some examples):

| Emoji | Code |
| --- | -- |
| :octocat:  | `:octocat:`  |
| :smiley:  |  `:smiley:`  |

Text formatting:
```
**This text will appear in bold**
_This text will appear in italics_
~~Strikethrough text~~
`This text will not be formatted`
> This text will become a quote
You can also @mention other users (@smileycreations15)
[This will become a link to GitHub.](https://github.com/)
```
Result:
> **This text will appear in bold**
> _This text will appear in italics_
> ~~Strikethrough text~~
> `This text will not be formatted`
> > This text will become a quote
> You can also @mention other users (@smileycreations15)
> [This will become a link to GitHub.](https://github.com/)

Instructions:
1. Create a file named `lesson3.md`
2. Place custom text with emojis and formatted text and links.
3. Click `Commit`
<hr>
<h3 align="center">Watch below your new pull request after creating the file for my response</h3>

**Comment by smileycreations88** [comment]
:octocat:

**Comment by smileycreations88** [comment]
Lesson3.md

**Comment by smileycreations88** [comment]
:lesson3.md:

**Comment by smileycreations15** [comment]
:octocat:
